syntax = "proto3";

option java_multiple_files = true;
option java_package = "cool.scx.live_room_watcher.impl.douyin_hack.proto.webcast.im";

package webcast.im;

import "douyin_hack/webcast/im/Common.proto";
import "douyin_hack/webcast/data/User.proto";

// 更新时间 : 2026-07-06, extracted from live-schema-im.aa08852d.js
message FansclubMessage {
    webcast.im.Common common = 1;
    int32 action = 2;
    string content = 3;
    webcast.data.User user = 4;
    UpgradePrivilege upgrade_privilege = 5;
    bytes public_area_common = 6;
    int64 left_diamond = 7;

    message UpgradePrivilege {
        string content = 1;
        string description = 2;
        int32 button_type = 3;
    }
}
